2013/07/12 18:38:59 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fahrenheit.profile_picture' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `profile_picture`.
in /Applications/XAMPP/xamppfiles/htdocs/fahrenheit/protected/views/user/index.php (510)
in /Applications/XAMPP/xamppfiles/htdocs/fahrenheit/protected/controllers/UserController.php (234)
in /Applications/XAMPP/xamppfiles/htdocs/fahrenheit/index.php (13)
2013/07/12 18:38:59 [error] [exception.CDbException] exception 'CDbException' with message 'The table "profile_picture" for active record class "ProfilePicture" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2310
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(ProfilePicture))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(402): CActiveRecord::model('ProfilePicture')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(77): CActiveRecord->getMetaData()
#3 /Applications/XAMPP/xamppfiles/htdocs/fahrenheit/protected/views/user/index.php(510): CActiveRecord->__construct()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/fahrenheit/protected/controllers/UserController.php(234): CController->render('index', Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): UserController->actionDashboard()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /Applications/XAMPP/xamppfiles/htdocs/fahrenheit/index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/fahrenheit/
HTTP_REFERER=http://localhost/fahrenheit/site/login
---
2013/07/12 18:45:48 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:179
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('cad')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/cad')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/fahrenheit/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/fahrenheit/user/cad
---
2013/07/12 18:46:29 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:179
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('cad')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/cad')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/fahrenheit/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/fahrenheit/user/cad
---
2013/07/12 18:51:38 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:179
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('cad')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/cad')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/fahrenheit/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/fahrenheit/user/cad
---
2013/07/13 01:36:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "teamsoft/files/t2689577.jpg".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('teamsoft/files/...')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/teamsoft/files/t2689577.jpg
HTTP_REFERER=http://localhost/
---
2013/07/13 01:36:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "teamsoft/files/t1436225470.png".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('teamsoft/files/...')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/teamsoft/files/t1436225470.png
HTTP_REFERER=http://localhost/
---
2013/07/13 01:36:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "teamsoft/files/t2689577.jpg".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('teamsoft/files/...')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/teamsoft/files/t2689577.jpg
HTTP_REFERER=http://localhost/
---
2013/07/13 01:36:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "teamsoft/files/t1436225470.png".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('teamsoft/files/...')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/teamsoft/files/t1436225470.png
HTTP_REFERER=http://localhost/
---
2013/07/13 01:36:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "teamsoft/files/t1436225470.png".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('teamsoft/files/...')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/teamsoft/files/t1436225470.png
HTTP_REFERER=http://localhost/
---
2013/07/13 01:37:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "files/t2689577.jpg".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('files/t2689577....')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/files/t2689577.jpg
HTTP_REFERER=http://localhost/
---
2013/07/13 01:37:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "files/t2689577.jpg".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('files/t2689577....')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/files/t2689577.jpg
HTTP_REFERER=http://localhost/
---
2013/07/13 01:38:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "teamsoft/status/create".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('teamsoft/status...')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/teamsoft/status/create
HTTP_REFERER=http://localhost/
---
2013/07/13 01:38:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "teamsoft/status/create".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('teamsoft/status...')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/teamsoft/status/create
HTTP_REFERER=http://localhost/
---
2013/07/13 01:41:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "files/t2689577.jpg".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('files/t2689577....')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/files/t2689577.jpg
HTTP_REFERER=http://localhost/
---
2013/07/13 01:41:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "files/t2689577.jpg".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('files/t2689577....')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/files/t2689577.jpg
HTTP_REFERER=http://localhost/
---
2013/07/13 01:41:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "files/t2689577.jpg".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('files/t2689577....')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/files/t2689577.jpg
HTTP_REFERER=http://localhost/
---
2013/07/13 01:41:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "files/t2689577.jpg".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('files/t2689577....')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/files/t2689577.jpg
HTTP_REFERER=http://localhost/
---
2013/07/13 01:45:32 [error] [exception.CException] exception 'CException' with message 'Property "CHttpRequest.basePath" is not defined.' in /opt/lampp/yii/framework/base/CComponent.php:130
Stack trace:
#0 /opt/lampp/testidocs/protected/views/status/_index.php(12): CComponent->__get('basePath')
#1 /opt/lampp/yii/framework/web/CBaseController.php(126): require('/opt/lampp/test...')
#2 /opt/lampp/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/opt/lampp/test...', Array, true)
#3 /opt/lampp/yii/framework/web/CController.php(869): CBaseController->renderFile('/opt/lampp/test...', Array, true)
#4 /opt/lampp/testidocs/protected/controllers/StatusController.php(75): CController->renderPartial('_index', Array)
#5 /opt/lampp/yii/framework/web/actions/CInlineAction.php(49): StatusController->actionCreate()
#6 /opt/lampp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /opt/lampp/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 /opt/lampp/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#9 /opt/lampp/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#10 /opt/lampp/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 /opt/lampp/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 /opt/lampp/yii/framework/web/CController.php(291): CFilterChain->run()
#13 /opt/lampp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /opt/lampp/yii/framework/web/CWebApplication.php(282): CController->run('create')
#15 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('status/create')
#16 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#17 /opt/lampp/testidocs/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/status/create
HTTP_REFERER=http://localhost/
---
2013/07/13 01:46:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "files/t2689577.jpg".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('files/t2689577....')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/files/t2689577.jpg
HTTP_REFERER=http://localhost/
---
2013/07/13 01:47:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in /opt/lampp/yii/framework/web/CController.php:483
Stack trace:
#0 /opt/lampp/yii/framework/web/CController.php(270): CController->missingAction('index')
#1 /opt/lampp/yii/framework/web/CWebApplication.php(282): CController->run('index')
#2 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/index')
#3 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /opt/lampp/testidocs/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/user/index
HTTP_REFERER=http://localhost/
---
2013/07/13 01:48:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "loading.gif".' in /opt/lampp/yii/framework/web/CController.php:483
Stack trace:
#0 /opt/lampp/yii/framework/web/CController.php(270): CController->missingAction('loading.gif')
#1 /opt/lampp/yii/framework/web/CWebApplication.php(282): CController->run('loading.gif')
#2 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/loading.gi...')
#3 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /opt/lampp/testidocs/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/user/loading.gif
HTTP_REFERER=http://localhost/user/dashboard
---
2013/07/13 01:48:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "files/t2689577.jpg".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('files/t2689577....')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/files/t2689577.jpg
HTTP_REFERER=http://localhost/user/dashboard
---
2013/07/13 01:48:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "loading.gif".' in /opt/lampp/yii/framework/web/CController.php:483
Stack trace:
#0 /opt/lampp/yii/framework/web/CController.php(270): CController->missingAction('loading.gif')
#1 /opt/lampp/yii/framework/web/CWebApplication.php(282): CController->run('loading.gif')
#2 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/loading.gi...')
#3 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /opt/lampp/testidocs/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/user/loading.gif
HTTP_REFERER=http://localhost/user/dashboard
---
2013/07/13 01:49:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "loading.gif".' in /opt/lampp/yii/framework/web/CController.php:483
Stack trace:
#0 /opt/lampp/yii/framework/web/CController.php(270): CController->missingAction('loading.gif')
#1 /opt/lampp/yii/framework/web/CWebApplication.php(282): CController->run('loading.gif')
#2 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/loading.gi...')
#3 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /opt/lampp/testidocs/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/user/loading.gif
HTTP_REFERER=http://localhost/user/dashboard
---
2013/07/13 01:50:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "loading.gif".' in /opt/lampp/yii/framework/web/CController.php:483
Stack trace:
#0 /opt/lampp/yii/framework/web/CController.php(270): CController->missingAction('loading.gif')
#1 /opt/lampp/yii/framework/web/CWebApplication.php(282): CController->run('loading.gif')
#2 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/loading.gi...')
#3 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /opt/lampp/testidocs/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/user/loading.gif
HTTP_REFERER=http://localhost/user/dashboard
---
2013/07/13 02:36:19 [error] [exception.CException] exception 'CException' with message 'Property "EJcrop.success" is not defined.' in /opt/lampp/yii/framework/base/CComponent.php:173
Stack trace:
#0 /opt/lampp/yii/framework/web/CWidgetFactory.php(161): CComponent->__set('success', 'js:alert("wow")')
#1 /opt/lampp/yii/framework/web/CBaseController.php(146): CWidgetFactory->createWidget(Object(ProfilePictureController), 'ext.jcrop.EJcro...', Array)
#2 /opt/lampp/yii/framework/web/CBaseController.php(172): CBaseController->createWidget('ext.jcrop.EJcro...', Array)
#3 /opt/lampp/testidocs/protected/views/profilePicture/crop.php(39): CBaseController->widget('ext.jcrop.EJcro...', Array)
#4 /opt/lampp/yii/framework/web/CBaseController.php(126): require('/opt/lampp/test...')
#5 /opt/lampp/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/opt/lampp/test...', Array, true)
#6 /opt/lampp/yii/framework/web/CController.php(869): CBaseController->renderFile('/opt/lampp/test...', Array, true)
#7 /opt/lampp/yii/framework/web/CController.php(782): CController->renderPartial('crop', Array, true)
#8 /opt/lampp/testidocs/protected/controllers/ProfilePictureController.php(242): CController->render('crop', Array)
#9 /opt/lampp/yii/framework/web/actions/CInlineAction.php(49): ProfilePictureController->actionCrop()
#10 /opt/lampp/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /opt/lampp/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 /opt/lampp/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#13 /opt/lampp/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 /opt/lampp/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 /opt/lampp/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 /opt/lampp/yii/framework/web/CController.php(291): CFilterChain->run()
#17 /opt/lampp/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /opt/lampp/yii/framework/web/CWebApplication.php(282): CController->run('crop')
#19 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('profilePicture/...')
#20 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /opt/lampp/testidocs/index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/profilePicture/crop
HTTP_REFERER=http://localhost/
---
2013/07/13 10:34:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "xampp".' in /opt/lampp/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('xampp')
#1 /opt/lampp/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /opt/lampp/testidocs/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/xampp/
---
